### ISSUE TITLE
Upgrade dependency ansible-nss-pam-ldap-configure to v1.0.3

### ISSUE THREAD

**Issue by spk83** [andrewrothstein/ansible-nss-pam-ldap-supervisord#1]
https://github.com/andrewrothstein/ansible-nss-pam-ldap-supervisord/blob/master/meta/main.yml#L29

https://github.com/andrewrothstein/ansible-nss-pam-ldap-configure/releases

**Comment by andrewrothstein** [comment]
upgraded dep to v1.0.4 and published to the galaxy as v1.0.2
